In [1]:
import numpy as np
x = np.array(
    [[0,0,1],
     [0,1,1],
     [1,0,1],
     [1,1,1],
     [1,0,1],
    
    [1,1,1]])
y=np.array([[0],
           [1],
           [1],
           [0],
           [1],
           [0]])
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivate(x):
    return x*(1-x)
def mse(y,ycap):
    return ((y-ycap)**2).mean()
np.random.seed(101)
w1 = 2*np.random.random((3,5))-1
w2 = 2*np.random.random((5,7))-1
w3 = 2*np.random.random((7,5))-1
w4 = 2*np.random.random((5,1))-1
def train(x,y,w,iter,conv=0.00000001):
    W1 = w[0]
    W2 = w[1]
    W3 = w[2]
    W4 = w[3]
    
    perr = 0 
    
    for i in range(iter):
        l1 = sigmoid(x.dot(W1))
        l2 = sigmoid(l1.dot(W2))
        l3 = sigmoid(l2.dot(W3))
        l4 = sigmoid(l3.dot(W4))
        
        cerr = mse(y,l4)
        
        if i%250==0:
            print("current error for every 250 iters",cerr)
        
        diff = abs(perr-cerr)
        
        j=0
        if diff<=conv:
            print("Training completed", i+1 ,"iters")
            j=1
            break 
            
        
        e4 = y - l4
        delta4 = e4*derivate(l4)
        e3 = delta4.dot(W4.T)
        delta3 = e3*derivate(l3)
        e2 = delta3.dot(W3.T)
        delta2 = e2*derivate(l2)
        e1 = delta2.dot(W2.T)
        delta1 = e1*derivate(l1)
        W1 += x.T.dot(delta1)
        W2 += l1.T.dot(delta2)
        W3 += l2.T.dot(delta3)
        W4 += l3.T.dot(delta4)
        perr=cerr
    if j==0:
        print("Training not yet completed")
    return [W1,W2,W3,W4]


In [2]:
theta = train(x,y,[w1,w2,w3,w4],10000)

current error for every 250 iters 0.2686089992882632
current error for every 250 iters 0.15941616879252862
current error for every 250 iters 0.12713600005857492
current error for every 250 iters 0.01222315546330645
current error for every 250 iters 0.001983824152421466
current error for every 250 iters 0.0009083194419106233
current error for every 250 iters 0.0005501558663063793
current error for every 250 iters 0.0003814480738743695
current error for every 250 iters 0.0002863818028939857
current error for every 250 iters 0.00022652427857625232
current error for every 250 iters 0.000185873980619259
current error for every 250 iters 0.00015671140570238737
current error for every 250 iters 0.00013490276297571077
current error for every 250 iters 0.00011805448026099366
current error for every 250 iters 0.00010469372854521265
current error for every 250 iters 9.386901053379987e-05
current error for every 250 iters 8.49406092612397e-05
current error for every 250 iters 7.746387117287474e-05

In [3]:
print(w1)

[[-1.79160702  3.36228665 -4.15277106 -1.1135678   2.04606174]
 [ 2.31550669 -2.71548858  4.07476616  0.06365725 -2.49872364]
 [ 0.72956785  0.9338406   1.01510335  0.98196087  1.0888418 ]]


In [4]:
theta[0]

array([[-1.79160702,  3.36228665, -4.15277106, -1.1135678 ,  2.04606174],
       [ 2.31550669, -2.71548858,  4.07476616,  0.06365725, -2.49872364],
       [ 0.72956785,  0.9338406 ,  1.01510335,  0.98196087,  1.0888418 ]])

In [13]:
def predict(x,w):
    r=x
    for v in w:
        r = sigmoid(r.dot(v))
    return r 

In [21]:
ycap = predict(x,theta)

In [22]:
len(k)

6

In [23]:
k

array([[0.00676432],
       [0.98797447],
       [0.99583239],
       [0.00475557],
       [0.99583239],
       [0.00475557]])

In [25]:
# its time to compare the machine predicted values and actual values
# y vs ycap

print(np.c_[y.ravel(),ycap.ravel()])

[[0.         0.00676432]
 [1.         0.98797447]
 [1.         0.99583239]
 [0.         0.00475557]
 [1.         0.99583239]
 [0.         0.00475557]]


In [26]:
# since our values are in probalities ,so we need to convert them in to labels
ycap[ycap>0.5]=1
ycap[ycap<0.5]=0

In [27]:
ycap

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.]])

In [29]:
print(np.c_[y.ravel(),ycap.ravel()])

[[0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]]


In [34]:
# NOW to validate our results we need to write accuracy function

def accuracy(y,ycap):
    r= y==ycap
    correctly_predicted =r[r==True].size
    n=y.size
    return (correctly_predicted/n)*100

In [35]:
accuracy(y,ycap)

100.0